name: Publish NuGet Packages

on:
    push:
        tags:
            - 'v*'

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: 📥 Checkout code
              uses: actions/checkout@v3

            - name: 🧰 Setup .NET SDK
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '8.x'

            - name: 🔄 Restore & Build
              run: dotnet build --configuration Release

            - name: 📦 Pack Luka packages
              run: |
                  dotnet pack src/Luka.Auth/src/Luka.Auth.csproj --configuration Release --output nupkgs
                  dotnet pack src/Luka.CQRS.Queries/src/Luka.CQRS.Queries.csproj --configuration Release --output nupkgs
                  dotnet pack src/Luka.Persistence.Postgre/src/Luka.Persistence.Postgre.csproj --configuration Release --output nupkgs
                  dotnet pack src/Luka.Persistence.Redis/src/Luka.Persistence.Redis.csproj --configuration Release --output nupkgs

            - name: 🚀 Push to NuGet
              run: dotnet nuget push "nupkgs/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
